.TH WCLIP 1 wclip\-VERSION
.SH NAME
wclip \- wayland clipboard manager
.SH SYNOPSIS
.B wclip
.RB [ \-i | \-o ]
.SH DESCRIPTION
wclip is a clipboard manager for wayland. It writes stdin to the selection or writes the selection to stdout.
.SH OPTIONS
.TP
.B \-i
Writes stdin to the selection. This is the default behavior.
.TP
.B \-o
Writes the selection to stdout.
